export const hotelTypes = [
  "Budget",
  "Boutique",
  "Luxury",
  "Ski Resort",
  "Business",
  "Family",
  "Romantic",
  "Hiking Resort",
  "Cabin",
  "Beach Resort",
  "Golf Resort",
  "Motel",
  "All Inclusive",
  "Pet Friendly",
  "Self Catering",
];

export const hotelType = [
  "Budget Hotel",
  "Mid-Range Hotel",
  "Luxury Hotel",
  "Boutique Hotel",
  "Resort Hotel",
  "Business Hotel",
  "Eco-Hotel",
  "Historical Hotel",
];

export const hotelFacilities = [
  "Free Wi-Fi",
  "Air Conditioning",
  "Heating",
  "TV",
  "Mini-bar",
  "Coffee Maker",
  "Ironing Board and Iron",
  "Hair Dryer",
  "Safe",
  "Fitness Center",
  "Swimming Pool",
  "Spa",
  "Business Center",
  "Restaurant",
  "Bar",
  "Laundry Service",
  "Valet Parking",
  "Concierge Service",
  "Pet-Friendly",
  "Smoking-Friendly",
  "Accessible Rooms",
];

export const roomType = [
  "Single Room",
  "Double Room",
  "Twin Room",
  "Triple Room",
  "Family Room",
  "Suite",
  "Studio",
  "Penthouse",
  "Connecting Room",
  "Accessible Room",
  "Non-Smoking Room",
  "Pet-Friendly Room",
  "Room with a View",
];

export const roomFacilities = [
  "Free Wi-Fi",
  "Air Conditioning",
  "Heating",
  "TV",
  "Mini-bar",
  "Coffee Maker",
  "Ironing Board and Iron",
  "Hair Dryer",
  "Safe",
  "Balcony or Patio",
  "View of City, Mountains, or Ocean",
  "Work Desk",
  "Extra Bed",
  "Sofa Bed",
  "Connecting Room",
  "Other Room Amenities",
];
